package Vehicles;

/**
 * Base abstract representation of a vehicle in the system.
 * Provides common attributes (plate number, make, model, production year, lease status) and shared behavior.
 * @author Ahmed Gara Ali
 * @version 1.0
 * @since 1.0
 * @see Vehicles.Car
 * @see Vehicles.Truck
 */
public class Vehicle {

    /** Unique plate number generated by subclasses. */
    protected String plateNumber; //Unique plate number of vehicle
    /** Manufacturer / brand of the vehicle. */
    protected String make;  //Brand name (or make)
    /** Model designation. */
    protected String model; // Vehicle model
    /** Year of production. */
    protected int prodyear; // Year of production
    /** Current lease status flag. */
    protected boolean isLeased;
   
    /**
     * Default constructor initializing empty vehicle.
     */
   public Vehicle(){

    this.plateNumber=null;
    this.make=null;
    this.model=null;
    this.prodyear=0;
    isLeased=false;
   }

   /**
    * Parameterized constructor.
    * @param make vehicle manufacturer
    * @param model vehicle model
    * @param prodyear production year
    */
   public Vehicle(String make, String model,int prodyear){

    this.plateNumber=null;
    this.make=make;
    this.model=model;
    this.prodyear=prodyear;
    isLeased=false;
    }

    /**
     * Copy constructor.
     * @param aVehicle vehicle to copy
     */
    public Vehicle (Vehicle aVehicle) { //This insures that only the subclasses can call the copy constructor

        this.make=aVehicle.make;
        this.model=aVehicle.model;
        this.prodyear=aVehicle.prodyear;
        this.isLeased = aVehicle.isLeased;
        }
    
   //Setters and Getter for plateNumber
    /**
     * @return plate number (may be null if not yet assigned)
     */
    public String getPlateNumber() {
        return plateNumber;
    }
    /**
     * @param plateNumber new plate number
     */
    public void setPlateNumber(String plateNumber) {
        this.plateNumber = plateNumber;
    }

    //Setter and Getter for make
    /** @return manufacturer */
    public String getMake() {
        return make;
    }
    /** @param make manufacturer */
    public void setMake(String make) {
        this.make = make;
    }

    //Setter and Getter for model
    /** @return model */
    public String getModel() {
        return model;
    }
    /** @param model model */
    public void setModel(String model) {
        this.model = model;
    }

    //Setter and Getter for prodYear
    /** @return production year */
    public int getProdyear() {
        return prodyear;
    }
    /** @param prodyear production year */
    public void setProdyear(int prodyear) {
        this.prodyear = prodyear;
    }

    /**
     * Checks if vehicle is currently leased.
     * @return true if leased, false otherwise
     */
    public boolean VehicleLeaseStatus(){
        return isLeased;
    }
    /**
     * Modify lease status.
     * @param t new lease status
     */
    public void ModifyLeaseStatus(boolean t){
            this.isLeased=t;
    }

    /**
     * String representation including all core attributes.
     * @return formatted vehicle details
     */
    public String toString(){

        return "\nPlate Number: "+this.plateNumber+"\nMake (Brand): "+this.make+"\nModel: "+this.model+"\nProduction Year: "+this.prodyear+"\nLease Status: "+(isLeased ? "Yes" : "No");
        } 

    /**
     * Equality test (ignores plate number uniqueness; compares class & fields).
     * @param aVehicle other vehicle
     * @return true if same runtime class and attribute values
     */
    public boolean equals(Vehicle aVehicle){
            if(aVehicle!=null){
            return  (this.getClass()==aVehicle.getClass() && 
                this.make.equals(aVehicle.make)&&
                this.model.equals(aVehicle.model) &&
                this.prodyear==aVehicle.prodyear && this.isLeased==aVehicle.isLeased);}

            else return false;
      }
    

    
}
